### ISSUE TITLE
Uncaught ReferenceError: dust is not defined  tpl.dust:1 

### ISSUE THREAD

**Issue by wzup** [avaly/dust-loader#4]
Doesn't work.

tpl.dust

```
<h1>Hello, {name}</h1>
```

webpack.config

```
    entry: {
        'index': './assets/js/index.dust.js',


    module: {
        loaders: [
            {
                test: /\.dust$/,
                loader: 'dust-loader'
            },
```

index.dust.js

```
'use strict';

const dust = require('dustjs-linkedin');
const tpl = require('../../views/tpl.dust');
```

Error In browser:

```
tpl.dust:1 Uncaught ReferenceError: dust is not defined
```

Compiled to and error is thrown here, there is no `dust` here:

```
module.exports = (function(dust){dust.register("views\/tpl",body_0);function body_0(chk,ctx){return chk.w("<h1>Hello, ").f(ctx.get(["name"], false),ctx,"h").w("</h1>");}body_0.__dustBody=!0;return body_0}(dust));


/*****************
 ** WEBPACK FOOTER
 ** ./views/tpl.dust
 ** module id = 7
 ** module chunks = 0
 **/
```

**Comment by rmariuzzo** [comment]
I'm facing the same issue. Need help.

**Comment by ItsCosmo** [comment]
This is because the dust-loader is expecting 'dust' to exist in the global namespace. In webpack, you can handle this in a couple of ways:

#1 Use the ProvidePlugin

    plugins: [
      new webpack.ProvidePlugin({
        dust: 'dustjs-linkedin'
      })
    ],

- OR -

#2 Use imports-loader when loading the template:

    require('imports?dust=dustjs-linkedin!../../views/tpl.dust');

**Comment by avaly** [comment]
Thanks @ItsCosmo! I updated the readme.
